# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x, 16.x]  # Adjust based on the latest LTS version
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install  # or npm ci if you have package-lock.json
    - name: Decode and display secrets
      run: |
        touch .env
        echo PORT= ${{ secrets.PORT }} >> .env
        echo MONGOURI= ${{ secrets.MONGOURI }} >> .env
        echo SECRET= ${{ secrets.SECRET }} >> .env
        echo EMAIL= ${{ secrets.EMAIL }} >> .env
        echo PASSWORD= ${{ secrets.PASSWORD }} >> .env
        echo "Contents of .env file:"
        cat .env
    - name: Display secrets
      run: cat .env
    - name: Debug .env file
      run: |
        echo "Current directory: $(pwd)"
        echo "Contents of .env file:"
        ls -la
        cat .env


